base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("shop/", include("shop.urls")),
]

shop/urls.py
from django.urls import path

from . import views

app_name = "shop"
urlpatterns = [
    path("", views.index, name="index"),
    path("course/<int:course_id>/", views.course_detail, name="course_detail"),
]

shop/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Category(models.Model):
    # id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255)
    # created_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

class Course(models.Model):
    # id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=300)
    price = models.FloatField()
    students_qty = models.IntegerField(default=0)
    reviews_qty = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    # reduced_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    # description = models.TextField()
    # image = models.ImageField(upload_to="courses/")

    def __str__(self):
        return self.title

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponse
from .models import Category, Course
# Create your views here.

def index(request):
    # return render(request, "shop/templates/index.html")
    courses = Course.objects.all()
    # return HttpResponse([str(course)+'<br/>' for course in courses])
    return render(request, "shop/course.html", {"courses": courses, "title": "Courses"})

def course_detail(request, course_id):
    # try:
    #     # course = Course.objects.get(id=course_id)
    #     course = Course.objects.get(pk=course_id)
    #     return render(request, "course_detail.html", {"course": course, "title": course.title})
    # except Course.DoesNotExist:
    #     # raise Http404("Course not found")
    #     return HttpResponse("Course not found", status=404)

    course = get_object_or_404(Course, pk=course_id)
    return render(request, "shop/course_detail.html", {"course": course, "title": course.title})

# def category_detail(request, category_id):
#     category = Category.objects.get(pk=category_id)
#     return render(request, "category_detail.html", {"category": category, "title": category.title})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{{ title }}{% endblock %}</title>
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"
    crossorigin="anonymous"
  />
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url "shop:index" %}">Courses Shop</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% comment %} <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
        </ul>
      </div> {% endcomment %}
    </div>
  </nav>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/shop/course.html
{% extends 'base.html' %} {% comment %} {% block title %}{{ title }}{% endblock
%} {% endcomment %} {% block content %}
<h1>Categories</h1>
<table class="table mt-5 table-bordered table-striped table-hover">
  <thead class="table-dark">
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Price</th>
      <th>Students Qty</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for course in courses %}
    <tr>
      <td>
        <a href="{% url 'shop:course_detail' course.id %}">
          {{ course.title }}
        </a>
      </td>
      <td>{{ course.category }}</td>
      <td>{{ course.price }}</td>
      <td>{{ course.students_qty }}</td>
      <td><button class="btn btn-primary">Buy</button></td>
    </tr>
  </tbody>
  {% endfor %}
</table>
{% endblock %}

templates/shop/course_detail.html
{% extends 'base.html' %}
{% block content %}
      <h1>{{ course.title }}</h1>
      <h2>{{ course.category }}</h2>
      <p>price = {{ course.price }}</p>
      <p>students_qty = {{ course.students_qty }}</p>
      <p>reviews_qty = {{ course.reviews_qty }}</p>
      <p>created_at = {{ course.created_at }}</p>
      <button class="btn btn-primary">Buy</button>
{% endblock %}